#!/bin/bash

set -eu

mkdir -p /var/backups/gp/sonarqube/conf \
         /var/backups/gp/sonarqube/data \
         /var/backups/gp/sonarqube/extensions \
         /var/backups/gp/sonarqube/lib/bundled-plugins
rsync -a --delete /opt/sonarqube/conf/                   /var/backups/gp/sonarqube/conf/
rsync -a --delete /opt/sonarqube/data/                   /var/backups/gp/sonarqube/data/
rsync -a --delete /opt/sonarqube/extensions/             /var/backups/gp/sonarqube/extensions/
rsync -a --delete /opt/sonarqube/lib/bundled-plugins/    /var/backups/gp/sonarqube/lib/bundled-plugins/
